name: CI

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.OS }}-mvn-cache-${{ hashFiles('pom.xml') }}
          path: |
            ~/.m2
          restore-keys: |
            ${{ runner.OS }}-mvn-cache-${{ hashFiles('pom.xml') }}
            ${{ runner.OS }}-mvn-cache-
      - name: Run tests & package
        run: mvn -B test package
